"use server";

import { BlueprintCard } from "@/components/agents/BlueprintCard";
import { OpenClawLogo, AutoGPTLogo, PythonLogo, CrewAILogo, N8nLogo, CustomAgentLogo } from "@/components/icons/BrandIcons";
import { createServerClient } from "@/lib/supabaseServer";
import { redirect } from "next/navigation";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

interface AgentNewPageProps {
    params: Promise<{
        orgSlug: string;
        projectSlug: string;
    }>
}

export default async function AgentNewPage({ params }: AgentNewPageProps) {
    const { orgSlug, projectSlug } = await params;

    // Fetch Project ID
    const supabase = await createServerClient();

    // 1. Get Org ID
    const { data: org } = await supabase.from('organizations').select('id').eq('slug', orgSlug).single();
    if (!org) redirect('/dashboard');

    // 2. Get Project ID (with Org Check)
    const { data: project } = await supabase
        .from('projects')
        .select('id')
        .eq('slug', projectSlug)
        .eq('organization_id', org.id)
        .single();

    if (!project) redirect(`/dashboard/organizations/${orgSlug}`);

    const projectId = project.id;

    const blueprints = [
        {
            id: "openclaw",
            title: "OpenClaw",
            description: "The autonomous operator that controls your computer. Perfect for local tasks and desktop automation.",
            icon: <OpenClawLogo className="w-6 h-6" />,
            features: [
                "Desktop Control",
                "File System Access",
                "App Interaction"
            ],
            isPopular: true
        },

        {
            id: "n8n",
            title: "n8n Workflow",
            description: "Build custom AI agents visually using a low-code workflow automation tool. Great for connecting apps.",
            icon: <N8nLogo className="w-6 h-6" />,
            features: [
                "Visual Builder",
                "LangChain Support",
                "300+ Integrations"
            ],
            isNew: true
        },
        {
            id: "autogpt",
            title: "AutoGPT",
            description: "The original autonomous agent. Recursively improves its own prompts to achieve goals.",
            icon: <AutoGPTLogo className="w-6 h-6" />,
            features: [
                "Recursive Thoughts",
                "Long-term Memory",
                "Internet Access"
            ]
        },
        {
            id: "crewai",
            title: "CrewAI",
            description: "Orchestrate a team of agents to work together on complex projects.",
            icon: <CrewAILogo className="w-6 h-6" />,
            features: [
                "Role-based Agents",
                "Task Delegation",
                "Collaborative"
            ]
        },
        {
            id: "python-interpreter",
            title: "Python Sandbox",
            description: "A secure environment for executing Python code generated by LLMs.",
            icon: <PythonLogo className="w-6 h-6" />,
            features: [
                "Code Execution",
                "Data Analysis",
                "Visualizations"
            ]
        },
        {
            id: "custom",
            title: "Custom Agent",
            description: "Build your own agent from scratch with custom prompts and tools.",
            icon: <CustomAgentLogo className="w-6 h-6" />,
            features: [
                "Custom System Prompt",
                "Tool Selection",
                "Model Configuration"
            ]
        }
    ];

    return (
        <div className="w-full max-w-5xl mx-auto px-6 py-8 space-y-8">
            <div className="flex items-center gap-2">
                <Link
                    href={`/dashboard/organizations/${orgSlug}/projects/${projectSlug}/agents`}
                    className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors"
                >
                    <ArrowLeft className="w-4 h-4" />
                    Back to Agents
                </Link>
            </div>

            <div className="space-y-0.5">
                <h1 className="text-lg font-semibold">Agent Marketplace</h1>
                <p className="text-xs text-muted-foreground">
                    Select a blueprint to deploy an autonomous agent. All agents include Shadow Mode protection.
                </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {blueprints.map((blueprint) => (
                    <BlueprintCard
                        key={blueprint.id}
                        {...blueprint}
                        projectId={projectId}
                        orgSlug={orgSlug}
                        projectSlug={projectSlug}
                    />
                ))}
            </div>
        </div>
    );
}
