-- Migration: Platform Commission Support
-- Description: Adds support for Cencori to collect a commission on the markup profit generated by users.
-- Created: 2026-05-06

ALTER TABLE public.rate_plans 
ADD COLUMN IF NOT EXISTS platform_commission_percentage NUMERIC(5, 2) DEFAULT 20.00;

-- Update existing plans to have a 20% commission if they don't have one
UPDATE public.rate_plans SET platform_commission_percentage = 20.00 WHERE platform_commission_percentage IS NULL;

-- Add platform_commission_usd to end_user_usage to track Cencori's cut of the retail profit
ALTER TABLE public.end_user_usage 
ADD COLUMN IF NOT EXISTS platform_commission_usd NUMERIC(30, 18) DEFAULT 0;
