export const siteConfig = {
  name: "cencori",
  url: "https://cencori.com",
  description:
    "Cencori is the infrastructure for AI production. Security, observability, and scale — all in one platform.",
  links: {
    github: "https://github.com/cencori",
    docs: "https://cencori.com/docs",
    getStartedUrl: "/signup",
    signInUrl: "/login",
    x: "https://x.com/cencori",
    youtube: "https://www.youtube.com/@cencori",
    products: {
      aiGateway: "/ai-gateway",
      models: "/ai/models",
      ai: "/ai",
      compute: "/compute",
      integrations: "/integration",
      workflow: "/workflow",
      storage: "/storage",
      audit: "/audit",
      knight: "/product-knight",
      sandbox: "/product-sandbox",
      insights: "/insights",
      network: "/product-network",
      edge: "/edge",
      scan: "https://scan.cencori.com",
      enterprise: "/solutions/enterprise",
      developerTools: "/developer-tools",
    },
    company: {
      about: "/about",
      blog: "/blog",
      careers: "/careers",
      changelog: "/changelog",
      contact: "/contact",
      customers: "/customers",
      events: "/events",
      examples: "/examples",
      newsletter: "/newsletter",
      partners: "/partners",
      shipped: "/shipped",
      privacyPolicy: "/privacy-policy",
    },
  },
};

export type SiteConfig = typeof siteConfig;
